version: "2.4"

services:
  quizz:
    image: decision-tree:latest
    volumes:
      - '/tmp/mindmups/:/mindmups/'
    environment:
      SLACK_TOKEN: ""
      FEEDBACK_USE_SLACK: "false"
      PERSISTENCE_TYPE: "file" #use file, memory or database
      FILESTORAGE_DIR: "/mindmups"
#      DB_HOST: "db"
#      DB_PORT: "5432"
#      DB_NAME: "tree"
#      DB_USERNAME: "postgres"
#      DB_PASSWORD: "password"
    links:
      - db
    ports:
      - 8080:8080

  db:
    image: library/postgres:13
    #    ports:
    #      - 5432:15432
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "tree"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
