version: "2.4"

services:
  quizz:
    image: otrebski/quizz:latest
    volumes:
      - '/tmp/mindmups/:/mindmups/'
    environment:
      SLACK_TOKEN: ""
      FEEDBACK_USE_SLACK: "false"
      FEEDBACK_USE_DB: "false"
      MINDMUP_STORAGE: "file" #use file, memory or database
      FILESTORAGE_DIR: "/mindmups"
#      DB_HOST: "db"
#      DB_PORT: "5432"
#      DB_NAME: "quizz"
#      DB_USERNAME: "postgres"
#      DB_PASSWORD: "password"
    links:
      - db
    ports:
      - 8080:80

  db:
    image: library/postgres:13
    #    ports:
    #      - 5432:15432
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "quizz"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
