
### List of quizzes
GET http://localhost:8080/api/quiz/

### Starting point of quizz testowy

GET http://localhost:8080/api/quiz/testowy/path/
### Starting point of quizz q1

GET http://localhost:8080/api/quiz/testowy/path/root;1;2.5dff82e0db5911eaa61dadd3f94d4398

### Quizz with answer electricity
GET http://localhost:8080/api/quiz/q1/path/root;electricity

### Quizz with answer electricity and checkLocal
GET http://localhost:8080/api/quiz/q1/path/root;electricity;checkLocal

### Quizz with answer electricity and checkLocal
GET http://localhost:8080/api/quiz/q1/path/root;electricity;checkLocal;buildingFuses;noPower

### Feedback
POST http://localhost:8080/api/feedback
Content-Type: application/json
Accept: */*

{
  "comment": "ddddd",
  "path": "a",
  "quizzId": "q1",
  "rate": "-1"
}

### Add
PUT http://localhost:8080/api/quiz/testowy
Content-Type: application/json
Accept: application/json

{
  "formatVersion": 3,
  "id": "root",
  "ideas": {
    "1": {
      "title": "Starting point",
      "id": 1,
      "ideas": {
        "1": {
          "title": "Step 1",
          "id": "2.5dff82e0db5911eaa61dadd3f94d4398",
          "ideas": {
            "1": {
              "title": "Step 1.1",
              "id": "4.5dff82e0db5911eaa61dadd3f94d4398",
              "attr": {
                "parentConnector": {
                  "label": "A1"
                }
              }
            },
            "2": {
              "title": "Step 1.2",
              "id": "5.5dff82e0db5911eaa61dadd3f94d4398",
              "attr": {
                "parentConnector": {
                  "label": "A2"
                }
              }
            }
          },
          "attr": {
            "parentConnector": {
              "label": "A1"
            }
          }
        },
        "11": {
          "title": "Step 2",
          "id": "3.5dff82e0db5911eaa61dadd3f94d4398",
          "ideas": {
            "1": {
              "title": "Step 2.1",
              "id": "6.5dff82e0db5911eaa61dadd3f94d4398",
              "attr": {
                "parentConnector": {
                  "label": "A1"
                }
              }
            },
            "2": {
              "title": "Step 2.2",
              "id": "7.5dff82e0db5911eaa61dadd3f94d4398",
              "attr": {
                "parentConnector": {
                  "label": "A2"
                }
              }
            }
          },
          "attr": {
            "parentConnector": {
              "label": "A2"
            }
          }
        }
      }
    }
  },
  "attr": {
    "theme": "topdownStandard"
  },
  "title": "Starting point"
}


### Delete
DELETE http://localhost:8080/api/quiz/t1
Content-Type: application/json
Accept: application/json

### validate - not mindmup
POST http://localhost:8080/api/quizz/validate/mindmup
Content-Type: application/json

[]


### validate - correct mindmup
POST http://localhost:8080/api/quizz/validate/mindmup
Content-Type: application/json
Accept: application/json

{
  "formatVersion": 3,
  "id": "root",
  "ideas": {
    "1": {
      "title": "Starting point",
      "id": 1,
      "ideas": {
        "1": {
          "title": "Step 1",
          "id": "2.5dff82e0db5911eaa61dadd3f94d4398",
          "ideas": {
            "1": {
              "title": "Step 1.1",
              "id": "4.5dff82e0db5911eaa61dadd3f94d4398",
              "attr": {
                "parentConnector": {
                  "label": "A1"
                }
              }
            },
            "2": {
              "title": "Step 1.2",
              "id": "5.5dff82e0db5911eaa61dadd3f94d4398",
              "attr": {
                "parentConnector": {
                  "label": "A2"
                }
              }
            }
          },
          "attr": {
            "parentConnector": {
              "label": "A1"
            }
          }
        },
        "11": {
          "title": "Step 2",
          "id": "3.5dff82e0db5911eaa61dadd3f94d4398",
          "ideas": {
            "1": {
              "title": "Step 2.1",
              "id": "6.5dff82e0db5911eaa61dadd3f94d4398",
              "attr": {
                "parentConnector": {
                  "label": "A1"
                }
              }
            },
            "2": {
              "title": "Step 2.2",
              "id": "7.5dff82e0db5911eaa61dadd3f94d4398",
              "attr": {
                "parentConnector": {
                  "label": "A2"
                }
              }
            }
          },
          "attr": {
            "parentConnector": {
              "label": "A2"
            }
          }
        }
      }
    }
  },
  "attr": {
    "theme": "topdownStandard"
  },
  "title": "Starting point"
}
